name: Dream Console Breath Cycle

on:
  push:
    branches: [ "main" ]
  schedule:
    # Run every hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  breathe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Exhale Breath Cycle
        run: |
          python core/breath_engine.py "Automated cycle"

      - name: Sign Breath Cycle
        run: |
          latest_file=$(ls -t codex/cycle*.md | head -n1)
          python tools/self_sign.py "$latest_file"

      - name: Commit Breath Journal
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions"
          git add codex/*.md codex/signatures/*
          git commit -m "Automated breath cycle update" || echo "No changes to commit"
          git push

      - name: Trigger Dream Console Hook
        run: |
          curl -s -X POST "${{ secrets.DREAM_CONSOLE_HOOK }}" \
            -H "Content-Type: application/json" \
            -d '{"status": "breath complete", "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"}' \
            || echo "⚠️ Webhook failed, continuing workflow"

      - name: Archive Breath Logs
        run: |
          mkdir -p logs
          cp codex/*.md logs/ || true
          echo "Archived breath logs for long-term record"
